config/routes.rb
Rails.application.routes.draw do
  get 'map/show'

  devise_for :users
  get 'position/getPosition', to: 'position#getPosition', as: 'get_position'
  get 'map/show', to: 'map#show', as: 'show_map'
  get 'position/save', to: 'position#save' 

  root 'position#getPosition'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def show
  	@results = Position.where({user: current_user.id})
  end
end

app/controllers/position_controller.rb
class PositionController < ApplicationController
  def getPosition
  	@positions = (Position.where({user: current_user.id}).reverse)[0,10]
  end

  def save
  	respond_to do |format|
	    latitud = params[:lat]
	    longitud = params[:lon]
	    puts "lon: "+longitud.to_str+" lat: "+latitud.to_str
	    @position = Position.new(user: current_user.id,latitud: latitud, longitud: longitud)
	    if @position.save
	          format.html { redirect_to get_position_path }
	    else
	        redirect_to get_position_path
	    end
	end

  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/position_helper.rb
module PositionHelper
end

app/views/event/get_date.html.erb
<body>
	
	<%= form_tag("/event/map", method: "get") do %>
	<%= label_tag(:starting, "Starting Date") %>
	<%= datetime_local_field(:starting, :date_1) %>
	<%= label_tag(:ending, "Ending Date") %>
	<%= datetime_local_field(:ending, :date_2) %>
	<%= submit_tag("Next") %>
	<%end%>

	<%= link_to "back", root_path, :method => :get %>
	
</body>

app/views/event/get_location.html.erb
<body>

<script>
//Checks if the browser supports geolocation.
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(storePosition);
    } else { 
        document.write("Geolocation is not supported by this browser.");
    }
}
/*
Used to print the current coordinates.
function showPosition(position) {
   
   document.write("Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude);
}
*/
//Sends the coordinates as an http request for them to be stored on the database.
function storePosition(position){
	window.open("store?latitude=" + position.coords.latitude +
		"&longitude=" + position.coords.longitude,"_self");
}
//Repeat the process every second.
window.setInterval(getLocation, 1000);
</script>

 Storing locations...

<br>
<%= link_to "map", event_get_date_path, :method => :get %> <br>
<%= link_to "back", root_path, :method => :get %>

</body>

app/views/event/map.html.erb
<h1>Event#map</h1>
<p>Find me in app/views/event/map.html.erb</p>

app/views/event/store.html.erb
<h1>Event#store</h1>
<p>Find me in app/views/event/store.html.erb</p>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "app", event_get_location_path, :method => :get %> <br>
<%= link_to "map", event_get_date_path, :method => :get %> <br>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<% else %>

<h1> Log in</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %> <br>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProyectoWeb</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header class="mb-2">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand" href="#">
        <img src="<%= asset_path 'trackerM.png'%>"  width="40" height="40" class="d-inline-block align-top" alt="">Tracker M
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#contenidoNavbar" aria-controls="contenidoNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if user_signed_in? then %>
      <div class="collapse navbar-collapse" id="contenidoNavbar">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="<%= get_position_path %>"> Track me! </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= show_map_path %>"> History </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#"> Close to me</a>
          </li>
        </ul>


        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

             <%= current_user.email %> &nbsp
           </a>  
           <div class="dropdown-menu">
            <%= link_to "Mi Perfil", '#', class:"dropdown-item", :remote=>true %>
            <%= link_to "Salir", destroy_user_session_path, :method=>:delete, class:"dropdown-item"%>
          </div>
        </li>
      </ul>

      <p>&nbsp&nbsp&nbsp&nbsp</p>
    </div>
    <% end %>
  </nav>  
</header>  

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/map/show.html.erb
<h1>Map#show</h1>
<p>Find me in app/views/map/show.html.erb</p>
<br>
<div id="map"></div>
<script>
  	function initMap(){
	    var positions = <%= raw @results.to_json %>;
	    var centroMap;
	    if(positions[0]!=null){
	      centroMap  = new google.maps.LatLng(positions[0].latitud,positions[0].longitud);
	    }else{
	      centroMap = new google.maps.LatLng(6.217, -75.567);
	    }
	    var options = {
	      zoom: 4,
	      center: centroMap
	    };
	    var myMap = new google.maps.Map(document.getElementById("map"), options);
	    var i;
	    for(i=0; i<positions.length; i++){
	      var pos = new google.maps.LatLng(positions[i].latitud, positions[i].longitud);
	      var mark = new google.maps.Marker({
	        position: pos,
	        map: myMap
	      });
	    }
  	}
</script>
<script 
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCe0d0tWZ9ErIv3r1YfnudfgyObTkL9DzM&callback=initMap" async defer> 
    </script>

app/views/position/getposition.html.erb
<h1>Position</h1>

<script>
	function getLocation() {
	    if (navigator.geolocation) {
	        navigator.geolocation.getCurrentPosition(sendPosition);
	    } else {
	        document.write("Geolocation is not supported by this browser.");
	    }
	}
	function showPosition(position) {
	    document.write("<br> Latitude: " + position.coords.latitude +
	    " Longitude: " + position.coords.longitude);
	}
	function sendPosition(position) {
		window.open("save?lat="+position.coords.latitude +"&lon="+position.coords.longitude,"_self");
	}
	setInterval(getLocation,1000);
</script>	


<% while !@positions.empty? %>
    <% coordinate = @positions.pop %>
    <br><h3> Coordinate <%= coordinate.id %> </h3>
    <ul>
    	<li> <b>UserId:</b> <%= coordinate.user %></li>
    	<li> <b>Latitude:</b> <%= coordinate.latitud %></li>
    	<li> <b>Longitude:</b> <%= coordinate.longitud %></li>
    </ul>
<% end %>

app/views/position/save.html.erb
<h1>Position#save</h1>
<p>Find me in app/views/position/save.html.erb</p>